set_property SRC_FILE_INFO {cfile:/home/szymon/Desktop/magister/aes/project_2/project_2.srcs/constrs_1/new/physical.xdc rfile:../../../project_2.srcs/constrs_1/new/physical.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports clk]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports tx]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets trng_inst/entropy_cell_gen[0].neoTRNG_cell_inst/inv_out_4]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets trng_inst/entropy_cell_gen[1].neoTRNG_cell_inst/inv_out_6]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets trng_inst/entropy_cell_gen[2].neoTRNG_cell_inst/inv_out_8]
